title: "Northern Light Speakers London UK"
email: wowthemesnet@gmail.com
timezone: UTC
baseurl: "/northernlightspeakers.org.uk"
permalink: "/:title/"
logo: 'assets/images/ToastmastersLogoColor (1).svg'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/sal.png'
    email: wowthemesnet@gmail.com
    web: https://toastmasterclub.org/clubdata.php?c=125
    description: "Empowering individuals to become effective communicators and leaders."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://toastmasterclub.org/clubdata.php?c=125
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  facebook: https://www.facebook.com/groups/1718337351751860/?locale=en_GB

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
